version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependabot update\n\nCLA: trivial\n\n"
      include: "scope"
    labels:
      - "dependencies"
      - "cla: trivial"
      - "approval: review pending"
    reviewers:
      - "openssl/committers"

  - package-ecosystem: docker
    directory: /test/quic-openssl-docker
    schedule:
      interval: daily
