name: "Build openssl interop container from master"

on:
  schedule:
    - cron:  '40 02 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_quay_container:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
         fetch-depth: 0
      - name: "log in to quay.io"
        run: |
          docker login -u openssl-ci+machine -p ${{ secrets.QUAY_IO_PASSWORD }} quay.io
      - name: "Build container"
        run: |
          cd test/quic-openssl-docker/
          docker build -t quay.io/openssl-ci/openssl-quic-interop:latest .
      - name: "Push to quay"
        run: |
          docker push quay.io/openssl-ci/openssl-quic-interop:latest

