name: "Trigger docs.openssl.org deployment"

on:
  push:
    branches:
      - "openssl-3.[0-9]+"
      - "master"
    paths:
      - "doc/man*/**"

permissions:
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: "Trigger deployment workflow"
        run: |
          gh workflow run -f branch=${{ github.ref_name }} deploy-site.yaml
          sleep 3
          RUN_ID=$(gh run list -w deploy-site.yaml -L 1 --json databaseId -q ".[0].databaseId")
          gh run watch ${RUN_ID} --exit-status
        env:
          GH_REPO: "openssl/openssl-docs"
          GH_TOKEN: ${{ secrets.OPENSSL_MACHINE_TOKEN }}
